### ISSUE TITLE
sdsl-lite not found

### ISSUE THREAD

**Issue by Tao-Tang** [farruggia/rlzap#1]
It seems module sdsl-lite not found during compile, I download sdsl-lite from github(https://github.com/simongog/sdsl-lite) and install it in /home/usr/include but it is still not found.
cmake .. returns:
-- g++ found
-- Updating submodules to their latest/fixed versions
-- (this can take a while, please be patient)
-- checking for one of the modules 'sdsl-lite'
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:363 (message):
  None of the required 'sdsl-lite' found
Call Stack (most recent call first):
  CMakeLists.txt:40 (pkg_search_module)

**Comment by jltsiren** [comment]
The documentation was out of date; I just updated it.

By default, RLZAP uses the version of SDSL found by `pkg-config`. If you have installed SDSL to your home directory, you may need to add `$HOME/lib/pkgconfig` to your `PKG_CONFIG_PATH`.

The alternative is to use the version of SDSL shipped as a submodule. You can do this by setting `RLZ_USE_EXTERNAL_SDSL` to `OFF` in `CMakeLists.txt`.

We don't use the SDSL submodule by default, because the default option is to compile RLZAP as a library. When a project uses multiple libraries depending on the SDSL, all libraries should use the same version of SDSL. The SDSL is a header-based library, and using multiple versions of the headers may lead to unpredictable issues. On the other hand, if you only need RLZAP as a standalone tool, using the SDSL submodule is safe.

**Comment by Tao-Tang** [comment]
Yeah, add "set(RLZ_USE_EXTERNAL_SDSL OFF)" in line 38 of CMakeLists.txt makes compile successful.  

However, the readme indicates that there will be an object file rlzap_build after make, but I can't find in directory, search its path in Makefile also failed.

**Comment by jltsiren** [comment]
You also need to set `RLZ_BINARIES` to `ON` to compile the tools. The default is to compile only the library.

**Comment by Tao-Tang** [comment]
That works, thanks a lot for help.
